### ISSUE TITLE
Tres Interessant

### ISSUE THREAD

**Issue by Andy-Ta** [roykhoury/Investrack#1]
🤔

**Comment by roykhoury** [comment]
😂😂

**Comment by roykhoury** [comment]
Yeah, does something like this exist?

**Comment by Andy-Ta** [comment]
What is this actually?

**Comment by roykhoury** [comment]
You enter, what currency you bought, when you bought it, % fees u paid ...from which exchange platform  etc 
Calculates how much you actually received, stores all ur transactions for you 
And calculate how much profit you’re making from all ur investments

**Comment by Andy-Ta** [comment]
Like Blockfolio?

**Comment by roykhoury** [comment]
Yeah, I guess so  😢 ,
but not on mobile
